# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'interfaceKPtsUy.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PyQt5.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1278, 725)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.horizontalLayout_3 = QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.main_horizontal = QHBoxLayout()
        self.main_horizontal.setSpacing(0)
        self.main_horizontal.setObjectName(u"main_horizontal")
        self.main_horizontal.setContentsMargins(0, 0, 10, -1)
        self.left_buttons_frame = QFrame(self.centralwidget)
        self.left_buttons_frame.setObjectName(u"left_buttons_frame")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(4)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.left_buttons_frame.sizePolicy().hasHeightForWidth())
        self.left_buttons_frame.setSizePolicy(sizePolicy1)
        self.left_buttons_frame.setFrameShape(QFrame.StyledPanel)
        self.left_buttons_frame.setFrameShadow(QFrame.Raised)
        self.ham_button_view = QPushButton(self.left_buttons_frame)
        self.ham_button_view.setObjectName(u"ham_button_view")
        self.ham_button_view.setGeometry(QRect(0, 110, 91, 50))
        self.ham_button_insert = QPushButton(self.left_buttons_frame)
        self.ham_button_insert.setObjectName(u"ham_button_insert")
        self.ham_button_insert.setGeometry(QRect(0, 160, 91, 50))
        self.ham_button_analytics = QPushButton(self.left_buttons_frame)
        self.ham_button_analytics.setObjectName(u"ham_button_analytics")
        self.ham_button_analytics.setGeometry(QRect(0, 210, 91, 50))
        self.ham_button_settings = QPushButton(self.left_buttons_frame)
        self.ham_button_settings.setObjectName(u"ham_button_settings")
        self.ham_button_settings.setGeometry(QRect(0, 310, 91, 50))
        self.ham_button_reports = QPushButton(self.left_buttons_frame)
        self.ham_button_reports.setObjectName(u"ham_button_reports")
        self.ham_button_reports.setGeometry(QRect(0, 260, 91, 50))
        self.ham_button_extra = QPushButton(self.left_buttons_frame)
        self.ham_button_extra.setObjectName(u"ham_button_extra")
        self.ham_button_extra.setGeometry(QRect(0, 360, 91, 50))

        self.main_horizontal.addWidget(self.left_buttons_frame)

        self.central_widget_frame = QFrame(self.centralwidget)
        self.central_widget_frame.setObjectName(u"central_widget_frame")
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy2.setHorizontalStretch(50)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.central_widget_frame.sizePolicy().hasHeightForWidth())
        self.central_widget_frame.setSizePolicy(sizePolicy2)
        self.central_widget_frame.setFrameShape(QFrame.StyledPanel)
        self.central_widget_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_4 = QHBoxLayout(self.central_widget_frame)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.stackedWidget = QStackedWidget(self.central_widget_frame)
        self.stackedWidget.setObjectName(u"stackedWidget")
        sizePolicy3 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(7)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy3)
        self.stacked_view_db_page = QWidget()
        self.stacked_view_db_page.setObjectName(u"stacked_view_db_page")
        sizePolicy.setHeightForWidth(self.stacked_view_db_page.sizePolicy().hasHeightForWidth())
        self.stacked_view_db_page.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QVBoxLayout(self.stacked_view_db_page)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.frame_6 = QFrame(self.stacked_view_db_page)
        self.frame_6.setObjectName(u"frame_6")
        sizePolicy4 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(1)
        sizePolicy4.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy4)
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.filter_clear_button = QPushButton(self.frame_6)
        self.filter_clear_button.setObjectName(u"filter_clear_button")
        self.filter_clear_button.setGeometry(QRect(520, 20, 75, 23))
        self.filter_column_button = QPushButton(self.frame_6)
        self.filter_column_button.setObjectName(u"filter_column_button")
        self.filter_column_button.setGeometry(QRect(280, 20, 111, 23))
        self.refresh_table_button = QPushButton(self.frame_6)
        self.refresh_table_button.setObjectName(u"refresh_table_button")
        self.refresh_table_button.setGeometry(QRect(10, 20, 101, 23))
        self.filter_user_text = QLineEdit(self.frame_6)
        self.filter_user_text.setObjectName(u"filter_user_text")
        self.filter_user_text.setGeometry(QRect(410, 20, 113, 20))
        self.filter_options_combobox = QComboBox(self.frame_6)
        self.filter_options_combobox.setObjectName(u"filter_options_combobox")
        self.filter_options_combobox.setGeometry(QRect(130, 20, 121, 22))

        self.verticalLayout_2.addWidget(self.frame_6)

        self.main_table = QTableWidget(self.stacked_view_db_page)
        self.main_table.setObjectName(u"main_table")
        sizePolicy5 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(10)
        sizePolicy5.setHeightForWidth(self.main_table.sizePolicy().hasHeightForWidth())
        self.main_table.setSizePolicy(sizePolicy5)

        self.verticalLayout_2.addWidget(self.main_table)

        self.frame_7 = QFrame(self.stacked_view_db_page)
        self.frame_7.setObjectName(u"frame_7")
        sizePolicy4.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy4)
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.checkbox_serial = QCheckBox(self.frame_7)
        self.checkbox_serial.setObjectName(u"checkbox_serial")
        self.checkbox_serial.setGeometry(QRect(110, 10, 81, 17))
        self.checkbox_name = QCheckBox(self.frame_7)
        self.checkbox_name.setObjectName(u"checkbox_name")
        self.checkbox_name.setGeometry(QRect(290, 10, 81, 17))
        self.checkbox_model = QCheckBox(self.frame_7)
        self.checkbox_model.setObjectName(u"checkbox_model")
        self.checkbox_model.setGeometry(QRect(110, 30, 81, 17))
        self.checkbox_notes = QCheckBox(self.frame_7)
        self.checkbox_notes.setObjectName(u"checkbox_notes")
        self.checkbox_notes.setGeometry(QRect(610, 10, 81, 17))
        self.checkbox_deploymentdate = QCheckBox(self.frame_7)
        self.checkbox_deploymentdate.setObjectName(u"checkbox_deploymentdate")
        self.checkbox_deploymentdate.setGeometry(QRect(390, 30, 111, 17))
        self.checkbox_replacementdate = QCheckBox(self.frame_7)
        self.checkbox_replacementdate.setObjectName(u"checkbox_replacementdate")
        self.checkbox_replacementdate.setGeometry(QRect(500, 10, 111, 17))
        self.checkbox_assetlocation = QCheckBox(self.frame_7)
        self.checkbox_assetlocation.setObjectName(u"checkbox_assetlocation")
        self.checkbox_assetlocation.setGeometry(QRect(290, 30, 91, 17))
        self.checkbox_cost = QCheckBox(self.frame_7)
        self.checkbox_cost.setObjectName(u"checkbox_cost")
        self.checkbox_cost.setGeometry(QRect(200, 10, 81, 17))
        self.checkbox_view_retired_assets = QCheckBox(self.frame_7)
        self.checkbox_view_retired_assets.setObjectName(u"checkbox_view_retired_assets")
        self.checkbox_view_retired_assets.setGeometry(QRect(500, 30, 121, 17))
        self.checkbox_manufacturer = QCheckBox(self.frame_7)
        self.checkbox_manufacturer.setObjectName(u"checkbox_manufacturer")
        self.checkbox_manufacturer.setGeometry(QRect(10, 30, 91, 17))
        self.checkbox_assetcategory = QCheckBox(self.frame_7)
        self.checkbox_assetcategory.setObjectName(u"checkbox_assetcategory")
        self.checkbox_assetcategory.setGeometry(QRect(390, 10, 101, 17))
        self.checkbox_assettype = QCheckBox(self.frame_7)
        self.checkbox_assettype.setObjectName(u"checkbox_assettype")
        self.checkbox_assettype.setGeometry(QRect(10, 10, 81, 17))
        self.checkbox_assignedto = QCheckBox(self.frame_7)
        self.checkbox_assignedto.setObjectName(u"checkbox_assignedto")
        self.checkbox_assignedto.setGeometry(QRect(200, 30, 81, 17))
        self.checkbox_is_local = QCheckBox(self.frame_7)
        self.checkbox_is_local.setObjectName(u"checkbox_is_local")
        self.checkbox_is_local.setGeometry(QRect(610, 30, 71, 16))

        self.verticalLayout_2.addWidget(self.frame_7)

        self.stackedWidget.addWidget(self.stacked_view_db_page)
        self.stacked_add_to_db_page = QWidget()
        self.stacked_add_to_db_page.setObjectName(u"stacked_add_to_db_page")
        self.insert_clear_selections_button = QPushButton(self.stacked_add_to_db_page)
        self.insert_clear_selections_button.setObjectName(u"insert_clear_selections_button")
        self.insert_clear_selections_button.setGeometry(QRect(1030, 610, 75, 23))
        self.insert_insert_button = QPushButton(self.stacked_add_to_db_page)
        self.insert_insert_button.setObjectName(u"insert_insert_button")
        self.insert_insert_button.setGeometry(QRect(140, 590, 131, 31))
        self.insert_asset_type_combobox = QComboBox(self.stacked_add_to_db_page)
        self.insert_asset_type_combobox.setObjectName(u"insert_asset_type_combobox")
        self.insert_asset_type_combobox.setGeometry(QRect(140, 100, 121, 22))
        self.insert_asset_type_add_option = QPushButton(self.stacked_add_to_db_page)
        self.insert_asset_type_add_option.setObjectName(u"insert_asset_type_add_option")
        self.insert_asset_type_add_option.setGeometry(QRect(270, 100, 21, 23))
        self.insert_manufacturer_combobox = QComboBox(self.stacked_add_to_db_page)
        self.insert_manufacturer_combobox.setObjectName(u"insert_manufacturer_combobox")
        self.insert_manufacturer_combobox.setGeometry(QRect(140, 140, 121, 22))
        self.insert_manufacturer_add_option = QPushButton(self.stacked_add_to_db_page)
        self.insert_manufacturer_add_option.setObjectName(u"insert_manufacturer_add_option")
        self.insert_manufacturer_add_option.setGeometry(QRect(270, 140, 21, 23))
        self.insert_serial_text = QLineEdit(self.stacked_add_to_db_page)
        self.insert_serial_text.setObjectName(u"insert_serial_text")
        self.insert_serial_text.setGeometry(QRect(140, 180, 121, 20))
        self.insert_serial_is_unique_button = QPushButton(self.stacked_add_to_db_page)
        self.insert_serial_is_unique_button.setObjectName(u"insert_serial_is_unique_button")
        self.insert_serial_is_unique_button.setGeometry(QRect(270, 180, 121, 23))
        self.insert_model_text = QLineEdit(self.stacked_add_to_db_page)
        self.insert_model_text.setObjectName(u"insert_model_text")
        self.insert_model_text.setGeometry(QRect(140, 220, 121, 20))
        self.insert_cost_spinbox = QDoubleSpinBox(self.stacked_add_to_db_page)
        self.insert_cost_spinbox.setObjectName(u"insert_cost_spinbox")
        self.insert_cost_spinbox.setGeometry(QRect(140, 250, 121, 22))
        self.insert_assigned_to_text = QLineEdit(self.stacked_add_to_db_page)
        self.insert_assigned_to_text.setObjectName(u"insert_assigned_to_text")
        self.insert_assigned_to_text.setGeometry(QRect(140, 280, 121, 20))
        self.insert_name_text = QLineEdit(self.stacked_add_to_db_page)
        self.insert_name_text.setObjectName(u"insert_name_text")
        self.insert_name_text.setGeometry(QRect(140, 310, 121, 20))
        self.insert_asset_location_combobox = QComboBox(self.stacked_add_to_db_page)
        self.insert_asset_location_combobox.setObjectName(u"insert_asset_location_combobox")
        self.insert_asset_location_combobox.setGeometry(QRect(140, 340, 121, 22))
        self.insert_asset_location_add_option = QPushButton(self.stacked_add_to_db_page)
        self.insert_asset_location_add_option.setObjectName(u"insert_asset_location_add_option")
        self.insert_asset_location_add_option.setGeometry(QRect(270, 340, 21, 23))
        self.insert_asset_category_add_option = QPushButton(self.stacked_add_to_db_page)
        self.insert_asset_category_add_option.setObjectName(u"insert_asset_category_add_option")
        self.insert_asset_category_add_option.setGeometry(QRect(270, 370, 21, 23))
        self.insert_asset_category_combobox = QComboBox(self.stacked_add_to_db_page)
        self.insert_asset_category_combobox.setObjectName(u"insert_asset_category_combobox")
        self.insert_asset_category_combobox.setGeometry(QRect(140, 370, 121, 22))
        self.insert_date_format_label = QLabel(self.stacked_add_to_db_page)
        self.insert_date_format_label.setObjectName(u"insert_date_format_label")
        self.insert_date_format_label.setGeometry(QRect(140, 400, 91, 16))
        self.insert_deployment_date_fmt = QDateEdit(self.stacked_add_to_db_page)
        self.insert_deployment_date_fmt.setObjectName(u"insert_deployment_date_fmt")
        self.insert_deployment_date_fmt.setGeometry(QRect(140, 430, 110, 22))
        self.insert_replacement_date_fmt = QDateEdit(self.stacked_add_to_db_page)
        self.insert_replacement_date_fmt.setObjectName(u"insert_replacement_date_fmt")
        self.insert_replacement_date_fmt.setGeometry(QRect(140, 470, 110, 22))
        self.insert_status_bool = QComboBox(self.stacked_add_to_db_page)
        self.insert_status_bool.setObjectName(u"insert_status_bool")
        self.insert_status_bool.setGeometry(QRect(140, 520, 101, 22))
        self.insert_conditional_status_frame = QFrame(self.stacked_add_to_db_page)
        self.insert_conditional_status_frame.setObjectName(u"insert_conditional_status_frame")
        self.insert_conditional_status_frame.setGeometry(QRect(270, 500, 241, 61))
        self.insert_conditional_status_frame.setFrameShape(QFrame.StyledPanel)
        self.insert_conditional_status_frame.setFrameShadow(QFrame.Raised)
        self.insert_conditional_retirement_date_fmt = QDateEdit(self.insert_conditional_status_frame)
        self.insert_conditional_retirement_date_fmt.setObjectName(u"insert_conditional_retirement_date_fmt")
        self.insert_conditional_retirement_date_fmt.setGeometry(QRect(110, 20, 110, 22))
        self.insert_retirement_date_label = QLabel(self.insert_conditional_status_frame)
        self.insert_retirement_date_label.setObjectName(u"insert_retirement_date_label")
        self.insert_retirement_date_label.setGeometry(QRect(10, 20, 91, 16))
        self.insert_notes_text = QTextEdit(self.stacked_add_to_db_page)
        self.insert_notes_text.setObjectName(u"insert_notes_text")
        self.insert_notes_text.setGeometry(QRect(550, 90, 291, 231))
        self.label_3 = QLabel(self.stacked_add_to_db_page)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(480, 100, 47, 13))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.insert_asset_type_label = QLabel(self.stacked_add_to_db_page)
        self.insert_asset_type_label.setObjectName(u"insert_asset_type_label")
        self.insert_asset_type_label.setGeometry(QRect(60, 100, 71, 20))
        self.insert_asset_type_label.setFont(font)
        self.insert_asset_type_label.setLayoutDirection(Qt.LeftToRight)
        self.insert_asset_type_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_manufacturer_label = QLabel(self.stacked_add_to_db_page)
        self.insert_manufacturer_label.setObjectName(u"insert_manufacturer_label")
        self.insert_manufacturer_label.setGeometry(QRect(40, 140, 91, 20))
        self.insert_manufacturer_label.setFont(font)
        self.insert_manufacturer_label.setLayoutDirection(Qt.LeftToRight)
        self.insert_manufacturer_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_serial_label = QLabel(self.stacked_add_to_db_page)
        self.insert_serial_label.setObjectName(u"insert_serial_label")
        self.insert_serial_label.setGeometry(QRect(66, 180, 61, 20))
        self.insert_serial_label.setFont(font)
        self.insert_serial_label.setLayoutDirection(Qt.LeftToRight)
        self.insert_serial_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_model_label = QLabel(self.stacked_add_to_db_page)
        self.insert_model_label.setObjectName(u"insert_model_label")
        self.insert_model_label.setGeometry(QRect(80, 220, 47, 13))
        self.insert_model_label.setFont(font)
        self.insert_model_label.setLayoutDirection(Qt.LeftToRight)
        self.insert_model_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_cost_label = QLabel(self.stacked_add_to_db_page)
        self.insert_cost_label.setObjectName(u"insert_cost_label")
        self.insert_cost_label.setGeometry(QRect(80, 255, 47, 13))
        self.insert_cost_label.setFont(font)
        self.insert_cost_label.setLayoutDirection(Qt.LeftToRight)
        self.insert_cost_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_assigned_to_label = QLabel(self.stacked_add_to_db_page)
        self.insert_assigned_to_label.setObjectName(u"insert_assigned_to_label")
        self.insert_assigned_to_label.setGeometry(QRect(60, 280, 71, 20))
        self.insert_assigned_to_label.setFont(font)
        self.insert_assigned_to_label.setLayoutDirection(Qt.LeftToRight)
        self.insert_assigned_to_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_name_label = QLabel(self.stacked_add_to_db_page)
        self.insert_name_label.setObjectName(u"insert_name_label")
        self.insert_name_label.setGeometry(QRect(46, 310, 81, 20))
        self.insert_name_label.setFont(font)
        self.insert_name_label.setLayoutDirection(Qt.LeftToRight)
        self.insert_name_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_asset_location_label = QLabel(self.stacked_add_to_db_page)
        self.insert_asset_location_label.setObjectName(u"insert_asset_location_label")
        self.insert_asset_location_label.setGeometry(QRect(36, 340, 91, 20))
        self.insert_asset_location_label.setFont(font)
        self.insert_asset_location_label.setLayoutDirection(Qt.LeftToRight)
        self.insert_asset_location_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_asset_category_label = QLabel(self.stacked_add_to_db_page)
        self.insert_asset_category_label.setObjectName(u"insert_asset_category_label")
        self.insert_asset_category_label.setGeometry(QRect(36, 370, 91, 20))
        self.insert_asset_category_label.setFont(font)
        self.insert_asset_category_label.setLayoutDirection(Qt.LeftToRight)
        self.insert_asset_category_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_deployment_date_label = QLabel(self.stacked_add_to_db_page)
        self.insert_deployment_date_label.setObjectName(u"insert_deployment_date_label")
        self.insert_deployment_date_label.setGeometry(QRect(30, 430, 101, 20))
        self.insert_deployment_date_label.setFont(font)
        self.insert_deployment_date_label.setLayoutDirection(Qt.LeftToRight)
        self.insert_deployment_date_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_replacement_date_label = QLabel(self.stacked_add_to_db_page)
        self.insert_replacement_date_label.setObjectName(u"insert_replacement_date_label")
        self.insert_replacement_date_label.setGeometry(QRect(20, 470, 111, 20))
        self.insert_replacement_date_label.setFont(font)
        self.insert_replacement_date_label.setLayoutDirection(Qt.LeftToRight)
        self.insert_replacement_date_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_status_label = QLabel(self.stacked_add_to_db_page)
        self.insert_status_label.setObjectName(u"insert_status_label")
        self.insert_status_label.setGeometry(QRect(70, 520, 61, 20))
        self.insert_status_label.setFont(font)
        self.insert_status_label.setLayoutDirection(Qt.LeftToRight)
        self.insert_status_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_is_local_label = QLabel(self.stacked_add_to_db_page)
        self.insert_is_local_label.setObjectName(u"insert_is_local_label")
        self.insert_is_local_label.setGeometry(QRect(50, 560, 81, 20))
        self.insert_is_local_label.setFont(font)
        self.insert_is_local_label.setLayoutDirection(Qt.LeftToRight)
        self.insert_is_local_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_is_local_checkbox = QCheckBox(self.stacked_add_to_db_page)
        self.insert_is_local_checkbox.setObjectName(u"insert_is_local_checkbox")
        self.insert_is_local_checkbox.setGeometry(QRect(140, 563, 16, 17))
        self.stackedWidget.addWidget(self.stacked_add_to_db_page)
        self.stacked_analytics = QWidget()
        self.stacked_analytics.setObjectName(u"stacked_analytics")
        self.analytics_graph_top = QFrame(self.stacked_analytics)
        self.analytics_graph_top.setObjectName(u"analytics_graph_top")
        self.analytics_graph_top.setGeometry(QRect(310, 50, 741, 291))
        self.analytics_graph_top.setFrameShape(QFrame.StyledPanel)
        self.analytics_graph_top.setFrameShadow(QFrame.Raised)
        self.analytics_field_combobox_top = QComboBox(self.stacked_analytics)
        self.analytics_field_combobox_top.setObjectName(u"analytics_field_combobox_top")
        self.analytics_field_combobox_top.setGeometry(QRect(100, 60, 111, 22))
        self.analytics_field_combobox_bottom = QComboBox(self.stacked_analytics)
        self.analytics_field_combobox_bottom.setObjectName(u"analytics_field_combobox_bottom")
        self.analytics_field_combobox_bottom.setGeometry(QRect(100, 110, 111, 22))
        self.analytics_update_top_view_button = QPushButton(self.stacked_analytics)
        self.analytics_update_top_view_button.setObjectName(u"analytics_update_top_view_button")
        self.analytics_update_top_view_button.setGeometry(QRect(120, 260, 75, 23))
        self.analytics_export_top_button = QPushButton(self.stacked_analytics)
        self.analytics_export_top_button.setObjectName(u"analytics_export_top_button")
        self.analytics_export_top_button.setGeometry(QRect(120, 310, 75, 23))
        self.calendarWidget = QCalendarWidget(self.stacked_analytics)
        self.calendarWidget.setObjectName(u"calendarWidget")
        self.calendarWidget.setGeometry(QRect(610, 370, 441, 271))
        self.calendarWidget.setNavigationBarVisible(False)
        self.calendarWidget.setDateEditEnabled(False)
        self.analytics_month_button_jan = QPushButton(self.stacked_analytics)
        self.analytics_month_button_jan.setObjectName(u"analytics_month_button_jan")
        self.analytics_month_button_jan.setGeometry(QRect(320, 400, 80, 40))
        self.analytics_month_button_feb = QPushButton(self.stacked_analytics)
        self.analytics_month_button_feb.setObjectName(u"analytics_month_button_feb")
        self.analytics_month_button_feb.setGeometry(QRect(400, 400, 80, 40))
        self.analytics_month_button_mar = QPushButton(self.stacked_analytics)
        self.analytics_month_button_mar.setObjectName(u"analytics_month_button_mar")
        self.analytics_month_button_mar.setGeometry(QRect(480, 400, 80, 40))
        self.analytics_month_button_jun = QPushButton(self.stacked_analytics)
        self.analytics_month_button_jun.setObjectName(u"analytics_month_button_jun")
        self.analytics_month_button_jun.setGeometry(QRect(480, 440, 80, 40))
        self.analytics_month_button_may = QPushButton(self.stacked_analytics)
        self.analytics_month_button_may.setObjectName(u"analytics_month_button_may")
        self.analytics_month_button_may.setGeometry(QRect(400, 440, 80, 40))
        self.analytics_month_button_apr = QPushButton(self.stacked_analytics)
        self.analytics_month_button_apr.setObjectName(u"analytics_month_button_apr")
        self.analytics_month_button_apr.setGeometry(QRect(320, 440, 80, 40))
        self.analytics_month_button_jul = QPushButton(self.stacked_analytics)
        self.analytics_month_button_jul.setObjectName(u"analytics_month_button_jul")
        self.analytics_month_button_jul.setGeometry(QRect(320, 480, 80, 40))
        self.analytics_month_button_sep = QPushButton(self.stacked_analytics)
        self.analytics_month_button_sep.setObjectName(u"analytics_month_button_sep")
        self.analytics_month_button_sep.setGeometry(QRect(480, 480, 80, 40))
        self.analytics_month_button_aug = QPushButton(self.stacked_analytics)
        self.analytics_month_button_aug.setObjectName(u"analytics_month_button_aug")
        self.analytics_month_button_aug.setGeometry(QRect(400, 480, 80, 40))
        self.analytics_month_button_dec = QPushButton(self.stacked_analytics)
        self.analytics_month_button_dec.setObjectName(u"analytics_month_button_dec")
        self.analytics_month_button_dec.setGeometry(QRect(480, 520, 80, 40))
        self.analytics_month_button_oct = QPushButton(self.stacked_analytics)
        self.analytics_month_button_oct.setObjectName(u"analytics_month_button_oct")
        self.analytics_month_button_oct.setGeometry(QRect(320, 520, 80, 40))
        self.analytics_month_button_nov = QPushButton(self.stacked_analytics)
        self.analytics_month_button_nov.setObjectName(u"analytics_month_button_nov")
        self.analytics_month_button_nov.setGeometry(QRect(400, 520, 80, 40))
        self.analytics_year_input = QLineEdit(self.stacked_analytics)
        self.analytics_year_input.setObjectName(u"analytics_year_input")
        self.analytics_year_input.setGeometry(QRect(400, 370, 71, 20))
        self.analytics_year_positive = QPushButton(self.stacked_analytics)
        self.analytics_year_positive.setObjectName(u"analytics_year_positive")
        self.analytics_year_positive.setGeometry(QRect(480, 370, 51, 23))
        self.analytics_year_negative = QPushButton(self.stacked_analytics)
        self.analytics_year_negative.setObjectName(u"analytics_year_negative")
        self.analytics_year_negative.setGeometry(QRect(354, 370, 41, 23))
        self.analytics_x_axis_text = QLineEdit(self.stacked_analytics)
        self.analytics_x_axis_text.setObjectName(u"analytics_x_axis_text")
        self.analytics_x_axis_text.setGeometry(QRect(100, 170, 113, 20))
        self.analytics_x_axis_label = QLabel(self.stacked_analytics)
        self.analytics_x_axis_label.setObjectName(u"analytics_x_axis_label")
        self.analytics_x_axis_label.setGeometry(QRect(100, 150, 101, 16))
        self.analytics_y_axis_label = QLabel(self.stacked_analytics)
        self.analytics_y_axis_label.setObjectName(u"analytics_y_axis_label")
        self.analytics_y_axis_label.setGeometry(QRect(100, 200, 101, 16))
        self.analytics_y_axis_text = QLineEdit(self.stacked_analytics)
        self.analytics_y_axis_text.setObjectName(u"analytics_y_axis_text")
        self.analytics_y_axis_text.setGeometry(QRect(100, 220, 113, 20))
        self.stackedWidget.addWidget(self.stacked_analytics)
        self.stacked_reports = QWidget()
        self.stacked_reports.setObjectName(u"stacked_reports")
        self.reports_export_frame = QFrame(self.stacked_reports)
        self.reports_export_frame.setObjectName(u"reports_export_frame")
        self.reports_export_frame.setGeometry(QRect(40, 20, 351, 631))
        self.reports_export_frame.setFrameShape(QFrame.StyledPanel)
        self.reports_export_frame.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.reports_export_frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(120, 20, 91, 31))
        font1 = QFont()
        font1.setPointSize(16)
        self.label.setFont(font1)
        self.reports_line_1 = QFrame(self.reports_export_frame)
        self.reports_line_1.setObjectName(u"reports_line_1")
        self.reports_line_1.setGeometry(QRect(0, 60, 341, 2))
        self.reports_line_1.setFrameShape(QFrame.StyledPanel)
        self.reports_line_1.setFrameShadow(QFrame.Raised)
        self.frame_3 = QFrame(self.reports_export_frame)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(0, 130, 341, 2))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.frame_4 = QFrame(self.reports_export_frame)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(10, 190, 341, 2))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.frame_5 = QFrame(self.reports_export_frame)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(0, 250, 341, 2))
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.reports_export_location_combobox = QComboBox(self.reports_export_frame)
        self.reports_export_location_combobox.setObjectName(u"reports_export_location_combobox")
        self.reports_export_location_combobox.setGeometry(QRect(200, 210, 91, 22))
        self.reports_export_export_active_radio = QRadioButton(self.reports_export_frame)
        self.reports_export_export_active_radio.setObjectName(u"reports_export_export_active_radio")
        self.reports_export_export_active_radio.setGeometry(QRect(20, 80, 131, 17))
        self.reports_export_export_retired_radio = QRadioButton(self.reports_export_frame)
        self.reports_export_export_retired_radio.setObjectName(u"reports_export_export_retired_radio")
        self.reports_export_export_retired_radio.setGeometry(QRect(20, 150, 131, 17))
        self.reports_export_export_location_radio = QRadioButton(self.reports_export_frame)
        self.reports_export_export_location_radio.setObjectName(u"reports_export_export_location_radio")
        self.reports_export_export_location_radio.setGeometry(QRect(20, 210, 161, 17))
        self.frame_8 = QFrame(self.reports_export_frame)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(0, 320, 341, 2))
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.reports_export_include_overdue_checkbox = QCheckBox(self.reports_export_frame)
        self.reports_export_include_overdue_checkbox.setObjectName(u"reports_export_include_overdue_checkbox")
        self.reports_export_include_overdue_checkbox.setGeometry(QRect(90, 390, 141, 21))
        self.frame_9 = QFrame(self.reports_export_frame)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setGeometry(QRect(0, 450, 351, 1))
        self.frame_9.setFrameShape(QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Raised)
        self.reports_export_export_changed_radio = QRadioButton(self.reports_export_frame)
        self.reports_export_export_changed_radio.setObjectName(u"reports_export_export_changed_radio")
        self.reports_export_export_changed_radio.setGeometry(QRect(20, 270, 161, 21))
        self.reports_export_export_changed_combo = QComboBox(self.reports_export_frame)
        self.reports_export_export_changed_combo.setObjectName(u"reports_export_export_changed_combo")
        self.reports_export_export_changed_combo.setGeometry(QRect(188, 290, 81, 22))
        self.report_export_export_changed_spinbox = QSpinBox(self.reports_export_frame)
        self.report_export_export_changed_spinbox.setObjectName(u"report_export_export_changed_spinbox")
        self.report_export_export_changed_spinbox.setGeometry(QRect(280, 290, 61, 22))
        self.reports_export_export_date_radio = QRadioButton(self.reports_export_frame)
        self.reports_export_export_date_radio.setObjectName(u"reports_export_export_date_radio")
        self.reports_export_export_date_radio.setGeometry(QRect(20, 330, 131, 16))
        self.reports_export_by_date_from = QDateEdit(self.reports_export_frame)
        self.reports_export_by_date_from.setObjectName(u"reports_export_by_date_from")
        self.reports_export_by_date_from.setGeometry(QRect(10, 360, 110, 22))
        self.reports_export_by_date_from.setCalendarPopup(True)
        self.label_16 = QLabel(self.reports_export_frame)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(130, 360, 51, 21))
        self.reports_export_by_date_until = QDateEdit(self.reports_export_frame)
        self.reports_export_by_date_until.setObjectName(u"reports_export_by_date_until")
        self.reports_export_by_date_until.setGeometry(QRect(170, 360, 110, 22))
        self.reports_export_by_date_until.setCalendarPopup(True)
        self.checkBox = QCheckBox(self.reports_export_frame)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(90, 420, 221, 17))
        self.reports_export_all_radio = QRadioButton(self.reports_export_frame)
        self.reports_export_all_radio.setObjectName(u"reports_export_all_radio")
        self.reports_export_all_radio.setGeometry(QRect(20, 470, 121, 17))
        self.reports_utilities_frame = QFrame(self.stacked_reports)
        self.reports_utilities_frame.setObjectName(u"reports_utilities_frame")
        self.reports_utilities_frame.setGeometry(QRect(690, 20, 421, 631))
        self.reports_utilities_frame.setFrameShape(QFrame.StyledPanel)
        self.reports_utilities_frame.setFrameShadow(QFrame.Raised)
        self.frame_10 = QFrame(self.reports_utilities_frame)
        self.frame_10.setObjectName(u"frame_10")
        self.frame_10.setGeometry(QRect(0, 110, 450, 2))
        self.frame_10.setFrameShape(QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QFrame.Raised)
        self.label_14 = QLabel(self.reports_utilities_frame)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(130, 20, 81, 21))
        self.label_14.setFont(font1)
        self.label_15 = QLabel(self.reports_utilities_frame)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 80, 91, 16))
        self.frame_11 = QFrame(self.reports_utilities_frame)
        self.frame_11.setObjectName(u"frame_11")
        self.frame_11.setGeometry(QRect(0, 50, 450, 2))
        self.frame_11.setFrameShape(QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QFrame.Raised)
        self.reports_utilities_compare_intune_file_dialog = QPushButton(self.reports_utilities_frame)
        self.reports_utilities_compare_intune_file_dialog.setObjectName(u"reports_utilities_compare_intune_file_dialog")
        self.reports_utilities_compare_intune_file_dialog.setGeometry(QRect(310, 80, 31, 23))
        self.reports_utilities_intune_file_path = QLineEdit(self.reports_utilities_frame)
        self.reports_utilities_intune_file_path.setObjectName(u"reports_utilities_intune_file_path")
        self.reports_utilities_intune_file_path.setGeometry(QRect(150, 80, 161, 20))
        self.reports_utilities_ip_site_comparison = QLabel(self.reports_utilities_frame)
        self.reports_utilities_ip_site_comparison.setObjectName(u"reports_utilities_ip_site_comparison")
        self.reports_utilities_ip_site_comparison.setGeometry(QRect(10, 130, 121, 16))
        self.reports_utilities_compare_ip_site_dialog = QPushButton(self.reports_utilities_frame)
        self.reports_utilities_compare_ip_site_dialog.setObjectName(u"reports_utilities_compare_ip_site_dialog")
        self.reports_utilities_compare_ip_site_dialog.setGeometry(QRect(310, 130, 31, 23))
        self.reports_utilities_ip_site__comparison_path = QLineEdit(self.reports_utilities_frame)
        self.reports_utilities_ip_site__comparison_path.setObjectName(u"reports_utilities_ip_site__comparison_path")
        self.reports_utilities_ip_site__comparison_path.setGeometry(QRect(150, 130, 161, 20))
        self.frame_13 = QFrame(self.reports_utilities_frame)
        self.frame_13.setObjectName(u"frame_13")
        self.frame_13.setGeometry(QRect(0, 160, 450, 2))
        self.frame_13.setFrameShape(QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QFrame.Raised)
        self.reports_utilities_intune_run_button = QPushButton(self.reports_utilities_frame)
        self.reports_utilities_intune_run_button.setObjectName(u"reports_utilities_intune_run_button")
        self.reports_utilities_intune_run_button.setGeometry(QRect(360, 80, 41, 23))
        self.reports_utilities_bitdef_run_button = QPushButton(self.reports_utilities_frame)
        self.reports_utilities_bitdef_run_button.setObjectName(u"reports_utilities_bitdef_run_button")
        self.reports_utilities_bitdef_run_button.setGeometry(QRect(360, 130, 41, 23))
        self.export_file_dialog_button = QPushButton(self.stacked_reports)
        self.export_file_dialog_button.setObjectName(u"export_file_dialog_button")
        self.export_file_dialog_button.setGeometry(QRect(640, 88, 31, 23))
        self.label_4 = QLabel(self.stacked_reports)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(420, 88, 61, 16))
        self.export_file_path_choice = QLineEdit(self.stacked_reports)
        self.export_file_path_choice.setObjectName(u"export_file_path_choice")
        self.export_file_path_choice.setGeometry(QRect(480, 88, 161, 20))
        self.reports_export_main_export_button = QPushButton(self.stacked_reports)
        self.reports_export_main_export_button.setObjectName(u"reports_export_main_export_button")
        self.reports_export_main_export_button.setGeometry(QRect(420, 110, 251, 31))
        self.reports_export_status_label = QLabel(self.stacked_reports)
        self.reports_export_status_label.setObjectName(u"reports_export_status_label")
        self.reports_export_status_label.setGeometry(QRect(420, 230, 47, 13))
        self.reports_export_status_content = QLabel(self.stacked_reports)
        self.reports_export_status_content.setObjectName(u"reports_export_status_content")
        self.reports_export_status_content.setGeometry(QRect(420, 250, 241, 191))
        self.reports_export_file_combobox = QComboBox(self.stacked_reports)
        self.reports_export_file_combobox.setObjectName(u"reports_export_file_combobox")
        self.reports_export_file_combobox.setGeometry(QRect(540, 160, 69, 22))
        self.label_2 = QLabel(self.stacked_reports)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(450, 160, 81, 16))
        self.stackedWidget.addWidget(self.stacked_reports)
        self.stacked_settings = QWidget()
        self.stacked_settings.setObjectName(u"stacked_settings")
        self.settings_backup_dir_label = QLabel(self.stacked_settings)
        self.settings_backup_dir_label.setObjectName(u"settings_backup_dir_label")
        self.settings_backup_dir_label.setGeometry(QRect(110, 80, 111, 16))
        self.settings_backup_dir_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.settings_darkmode_label = QLabel(self.stacked_settings)
        self.settings_darkmode_label.setObjectName(u"settings_darkmode_label")
        self.settings_darkmode_label.setGeometry(QRect(130, 110, 91, 16))
        self.settings_darkmode_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.settings_report_auto_open_label = QLabel(self.stacked_settings)
        self.settings_report_auto_open_label.setObjectName(u"settings_report_auto_open_label")
        self.settings_report_auto_open_label.setGeometry(QRect(70, 140, 151, 16))
        self.settings_report_auto_open_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.settings_file_dialog_button = QPushButton(self.stacked_settings)
        self.settings_file_dialog_button.setObjectName(u"settings_file_dialog_button")
        self.settings_file_dialog_button.setGeometry(QRect(400, 80, 21, 23))
        self.settings_darkmode_checkbox = QCheckBox(self.stacked_settings)
        self.settings_darkmode_checkbox.setObjectName(u"settings_darkmode_checkbox")
        self.settings_darkmode_checkbox.setGeometry(QRect(230, 110, 70, 17))
        self.settings_report_auto_open_checkbox = QCheckBox(self.stacked_settings)
        self.settings_report_auto_open_checkbox.setObjectName(u"settings_report_auto_open_checkbox")
        self.settings_report_auto_open_checkbox.setGeometry(QRect(230, 140, 70, 17))
        self.settings_backup_dir_text = QLineEdit(self.stacked_settings)
        self.settings_backup_dir_text.setObjectName(u"settings_backup_dir_text")
        self.settings_backup_dir_text.setGeometry(QRect(230, 80, 171, 20))
        self.settings_update_button = QPushButton(self.stacked_settings)
        self.settings_update_button.setObjectName(u"settings_update_button")
        self.settings_update_button.setGeometry(QRect(880, 630, 241, 23))
        self.settings_ip_label = QLabel(self.stacked_settings)
        self.settings_ip_label.setObjectName(u"settings_ip_label")
        self.settings_ip_label.setGeometry(QRect(600, 80, 111, 20))
        self.settings_ip_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.settings_ip_text = QLineEdit(self.stacked_settings)
        self.settings_ip_text.setObjectName(u"settings_ip_text")
        self.settings_ip_text.setGeometry(QRect(720, 80, 113, 20))
        self.settings_switch_to_main_on_insert_checkbox = QCheckBox(self.stacked_settings)
        self.settings_switch_to_main_on_insert_checkbox.setObjectName(u"settings_switch_to_main_on_insert_checkbox")
        self.settings_switch_to_main_on_insert_checkbox.setGeometry(QRect(230, 180, 21, 17))
        self.settings_switch_to_main_on_insert_label = QLabel(self.stacked_settings)
        self.settings_switch_to_main_on_insert_label.setObjectName(u"settings_switch_to_main_on_insert_label")
        self.settings_switch_to_main_on_insert_label.setGeometry(QRect(80, 180, 141, 16))
        self.label_5 = QLabel(self.stacked_settings)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(610, 120, 371, 41))
        font2 = QFont()
        font2.setPointSize(18)
        self.label_5.setFont(font2)
        self.label_6 = QLabel(self.stacked_settings)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(610, 150, 401, 31))
        self.label_7 = QLabel(self.stacked_settings)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(610, 180, 311, 41))
        self.label_7.setTextFormat(Qt.RichText)
        self.label_7.setWordWrap(True)
        self.label_8 = QLabel(self.stacked_settings)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(610, 240, 211, 31))
        self.label_9 = QLabel(self.stacked_settings)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(610, 280, 291, 16))
        self.label_10 = QLabel(self.stacked_settings)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(610, 310, 281, 41))
        self.label_11 = QLabel(self.stacked_settings)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(610, 390, 251, 16))
        self.label_12 = QLabel(self.stacked_settings)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(610, 420, 321, 16))
        self.label_13 = QLabel(self.stacked_settings)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(610, 450, 321, 16))
        self.stackedWidget.addWidget(self.stacked_settings)
        self.stacked_extras = QWidget()
        self.stacked_extras.setObjectName(u"stacked_extras")
        self.extra_refresh_button = QPushButton(self.stacked_extras)
        self.extra_refresh_button.setObjectName(u"extra_refresh_button")
        self.extra_refresh_button.setGeometry(QRect(60, 30, 75, 23))
        self.extra_add_new_button = QPushButton(self.stacked_extras)
        self.extra_add_new_button.setObjectName(u"extra_add_new_button")
        self.extra_add_new_button.setGeometry(QRect(50, 530, 75, 23))
        self.extra_table = QTableWidget(self.stacked_extras)
        self.extra_table.setObjectName(u"extra_table")
        self.extra_table.setGeometry(QRect(60, 60, 941, 461))
        self.extra_log_frame = QFrame(self.stacked_extras)
        self.extra_log_frame.setObjectName(u"extra_log_frame")
        self.extra_log_frame.setGeometry(QRect(690, 520, 441, 141))
        self.extra_log_frame.setFrameShape(QFrame.StyledPanel)
        self.extra_log_frame.setFrameShadow(QFrame.Raised)
        self.stackedWidget.addWidget(self.stacked_extras)

        self.horizontalLayout_4.addWidget(self.stackedWidget)


        self.main_horizontal.addWidget(self.central_widget_frame)


        self.horizontalLayout_3.addLayout(self.main_horizontal)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(5)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.ham_button_view.setText(QCoreApplication.translate("MainWindow", u"Assets", None))
        self.ham_button_insert.setText(QCoreApplication.translate("MainWindow", u"Insert", None))
        self.ham_button_analytics.setText(QCoreApplication.translate("MainWindow", u"Analytics", None))
        self.ham_button_settings.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.ham_button_reports.setText(QCoreApplication.translate("MainWindow", u"Reports", None))
        self.ham_button_extra.setText(QCoreApplication.translate("MainWindow", u"Extra Inv", None))
        self.filter_clear_button.setText(QCoreApplication.translate("MainWindow", u"clear filter", None))
        self.filter_column_button.setText(QCoreApplication.translate("MainWindow", u"Apply Filter", None))
        self.refresh_table_button.setText(QCoreApplication.translate("MainWindow", u"Refresh Table", None))
        self.checkbox_serial.setText(QCoreApplication.translate("MainWindow", u"Serial", None))
        self.checkbox_name.setText(QCoreApplication.translate("MainWindow", u"Device Name", None))
        self.checkbox_model.setText(QCoreApplication.translate("MainWindow", u"Model", None))
        self.checkbox_notes.setText(QCoreApplication.translate("MainWindow", u"Notes", None))
        self.checkbox_deploymentdate.setText(QCoreApplication.translate("MainWindow", u"Deploymeny Date", None))
        self.checkbox_replacementdate.setText(QCoreApplication.translate("MainWindow", u"Replacement Date", None))
        self.checkbox_assetlocation.setText(QCoreApplication.translate("MainWindow", u"Asset Location", None))
        self.checkbox_cost.setText(QCoreApplication.translate("MainWindow", u"Cost", None))
        self.checkbox_view_retired_assets.setText(QCoreApplication.translate("MainWindow", u"Retired Assets", None))
        self.checkbox_manufacturer.setText(QCoreApplication.translate("MainWindow", u"Manufacturer", None))
        self.checkbox_assetcategory.setText(QCoreApplication.translate("MainWindow", u"Asset Category", None))
        self.checkbox_assettype.setText(QCoreApplication.translate("MainWindow", u"Asset Type", None))
        self.checkbox_assignedto.setText(QCoreApplication.translate("MainWindow", u"Asigned To", None))
        self.checkbox_is_local.setText(QCoreApplication.translate("MainWindow", u"Is Local", None))
        self.insert_clear_selections_button.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.insert_insert_button.setText(QCoreApplication.translate("MainWindow", u"Insert", None))
        self.insert_asset_type_add_option.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.insert_manufacturer_add_option.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.insert_serial_is_unique_button.setText(QCoreApplication.translate("MainWindow", u"Can't import empty S/N", None))
        self.insert_asset_location_add_option.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.insert_asset_category_add_option.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.insert_date_format_label.setText(QCoreApplication.translate("MainWindow", u"YYYY-MM-DD", None))
        self.insert_retirement_date_label.setText(QCoreApplication.translate("MainWindow", u"Retirement Date", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Notes", None))
        self.insert_asset_type_label.setText(QCoreApplication.translate("MainWindow", u"Asset Type", None))
        self.insert_manufacturer_label.setText(QCoreApplication.translate("MainWindow", u"Manufacturer", None))
        self.insert_serial_label.setText(QCoreApplication.translate("MainWindow", u"Serial #", None))
        self.insert_model_label.setText(QCoreApplication.translate("MainWindow", u"Model", None))
        self.insert_cost_label.setText(QCoreApplication.translate("MainWindow", u"Cost", None))
        self.insert_assigned_to_label.setText(QCoreApplication.translate("MainWindow", u"Assigned To", None))
        self.insert_name_label.setText(QCoreApplication.translate("MainWindow", u"Device Name", None))
        self.insert_asset_location_label.setText(QCoreApplication.translate("MainWindow", u"Asset Location", None))
        self.insert_asset_category_label.setText(QCoreApplication.translate("MainWindow", u"Asset Category", None))
        self.insert_deployment_date_label.setText(QCoreApplication.translate("MainWindow", u"Deployment Date", None))
        self.insert_replacement_date_label.setText(QCoreApplication.translate("MainWindow", u"Replacement Date", None))
        self.insert_status_label.setText(QCoreApplication.translate("MainWindow", u"Status", None))
        self.insert_is_local_label.setText(QCoreApplication.translate("MainWindow", u"Local Account", None))
        self.insert_is_local_checkbox.setText("")
        self.analytics_update_top_view_button.setText(QCoreApplication.translate("MainWindow", u"Upate View", None))
        self.analytics_export_top_button.setText(QCoreApplication.translate("MainWindow", u"Export graph", None))
        self.analytics_month_button_jan.setText(QCoreApplication.translate("MainWindow", u"January", None))
        self.analytics_month_button_feb.setText(QCoreApplication.translate("MainWindow", u"February", None))
        self.analytics_month_button_mar.setText(QCoreApplication.translate("MainWindow", u"March", None))
        self.analytics_month_button_jun.setText(QCoreApplication.translate("MainWindow", u"June", None))
        self.analytics_month_button_may.setText(QCoreApplication.translate("MainWindow", u"May", None))
        self.analytics_month_button_apr.setText(QCoreApplication.translate("MainWindow", u"April", None))
        self.analytics_month_button_jul.setText(QCoreApplication.translate("MainWindow", u"July", None))
        self.analytics_month_button_sep.setText(QCoreApplication.translate("MainWindow", u"September", None))
        self.analytics_month_button_aug.setText(QCoreApplication.translate("MainWindow", u"August", None))
        self.analytics_month_button_dec.setText(QCoreApplication.translate("MainWindow", u"December", None))
        self.analytics_month_button_oct.setText(QCoreApplication.translate("MainWindow", u"October", None))
        self.analytics_month_button_nov.setText(QCoreApplication.translate("MainWindow", u"November", None))
        self.analytics_year_positive.setText(QCoreApplication.translate("MainWindow", u"-->", None))
        self.analytics_year_negative.setText(QCoreApplication.translate("MainWindow", u"<---", None))
        self.analytics_x_axis_label.setText(QCoreApplication.translate("MainWindow", u"X Axis Values", None))
        self.analytics_y_axis_label.setText(QCoreApplication.translate("MainWindow", u"Y Axis Values", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.reports_export_export_active_radio.setText(QCoreApplication.translate("MainWindow", u"Export active assets", None))
        self.reports_export_export_retired_radio.setText(QCoreApplication.translate("MainWindow", u"Export retired assets", None))
        self.reports_export_export_location_radio.setText(QCoreApplication.translate("MainWindow", u"Export active By location", None))
        self.reports_export_include_overdue_checkbox.setText(QCoreApplication.translate("MainWindow", u"Include overdue assets", None))
        self.reports_export_export_changed_radio.setText(QCoreApplication.translate("MainWindow", u"Export changed (by month)", None))
        self.reports_export_export_date_radio.setText(QCoreApplication.translate("MainWindow", u"Due for replacement", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Until", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"Include unknown replacement date", None))
        self.reports_export_all_radio.setText(QCoreApplication.translate("MainWindow", u"Export All (backup)", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Utilities", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Intune Comparison", None))
        self.reports_utilities_compare_intune_file_dialog.setText(QCoreApplication.translate("MainWindow", u"..", None))
        self.reports_utilities_ip_site_comparison.setText(QCoreApplication.translate("MainWindow", u"IP/Site Comparison", None))
        self.reports_utilities_compare_ip_site_dialog.setText(QCoreApplication.translate("MainWindow", u"..", None))
        self.reports_utilities_intune_run_button.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.reports_utilities_bitdef_run_button.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.export_file_dialog_button.setText(QCoreApplication.translate("MainWindow", u"..", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Export Path:", None))
        self.reports_export_main_export_button.setText(QCoreApplication.translate("MainWindow", u"Export!", None))
        self.reports_export_status_label.setText(QCoreApplication.translate("MainWindow", u"Status:", None))
        self.reports_export_status_content.setText("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Export File Type", None))
        self.settings_backup_dir_label.setText(QCoreApplication.translate("MainWindow", u"Backup Directory Path", None))
        self.settings_darkmode_label.setText(QCoreApplication.translate("MainWindow", u"Dark Mode", None))
        self.settings_report_auto_open_label.setText(QCoreApplication.translate("MainWindow", u"Auto-open report in explorer", None))
        self.settings_file_dialog_button.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.settings_darkmode_checkbox.setText("")
        self.settings_report_auto_open_checkbox.setText("")
        self.settings_update_button.setText(QCoreApplication.translate("MainWindow", u"UPDATE!!", None))
        self.settings_ip_label.setText(QCoreApplication.translate("MainWindow", u"Invisman Server IP", None))
        self.settings_switch_to_main_on_insert_checkbox.setText("")
        self.settings_switch_to_main_on_insert_label.setText(QCoreApplication.translate("MainWindow", u"Auto-switch to main on insert", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"About Credentials / Connecting", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"This is an application made for windows, this will not work on linux", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"You must set 2 credentials in your window's credential manager. This is done from the \"Windows Credential\" option, and \"Add a generic credential\" ", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Internet or network address: . . . invisman", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Username: . . . . . . . . . . . . . . . The user name for the db", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Password: . . . . . . . . . . . . .  . . Password for the db", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Internet or network Address: . . . invisman_sshkey", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Username: . . . . . . . . . . . . . . . <Path to private sshkey>", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Password: . . . . . . . . . . . . . . . Passphrase for the private key", None))
        self.extra_refresh_button.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.extra_add_new_button.setText(QCoreApplication.translate("MainWindow", u"Add New", None))
    # retranslateUi

