# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'inventory_managerBqiifh.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PyQt5.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1302, 725)
        self.actionInsert = QAction(MainWindow)
        self.actionInsert.setObjectName(u"actionInsert")
        self.actionSettings = QAction(MainWindow)
        self.actionSettings.setObjectName(u"actionSettings")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionCreate_Backup = QAction(MainWindow)
        self.actionCreate_Backup.setObjectName(u"actionCreate_Backup")
        self.actionClose_ALT_F4 = QAction(MainWindow)
        self.actionClose_ALT_F4.setObjectName(u"actionClose_ALT_F4")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(100, 0, 1171, 661))
        self.stacked_view_db_page = QWidget()
        self.stacked_view_db_page.setObjectName(u"stacked_view_db_page")
        self.main_table = QTableWidget(self.stacked_view_db_page)
        self.main_table.setObjectName(u"main_table")
        self.main_table.setGeometry(QRect(10, 60, 1151, 550))
        self.refresh_table_button = QPushButton(self.stacked_view_db_page)
        self.refresh_table_button.setObjectName(u"refresh_table_button")
        self.refresh_table_button.setGeometry(QRect(10, 30, 75, 23))
        self.view_toggle_frame = QFrame(self.stacked_view_db_page)
        self.view_toggle_frame.setObjectName(u"view_toggle_frame")
        self.view_toggle_frame.setGeometry(QRect(10, 610, 800, 40))
        self.view_toggle_frame.setFrameShape(QFrame.StyledPanel)
        self.view_toggle_frame.setFrameShadow(QFrame.Raised)
        self.view_columns_button = QPushButton(self.view_toggle_frame)
        self.view_columns_button.setObjectName(u"view_columns_button")
        self.view_columns_button.setGeometry(QRect(0, 10, 75, 23))
        self.checkbox_serial = QCheckBox(self.view_toggle_frame)
        self.checkbox_serial.setObjectName(u"checkbox_serial")
        self.checkbox_serial.setGeometry(QRect(190, 0, 61, 21))
        self.checkbox_manufacturer = QCheckBox(self.view_toggle_frame)
        self.checkbox_manufacturer.setObjectName(u"checkbox_manufacturer")
        self.checkbox_manufacturer.setGeometry(QRect(100, 20, 91, 21))
        self.checkbox_cost = QCheckBox(self.view_toggle_frame)
        self.checkbox_cost.setObjectName(u"checkbox_cost")
        self.checkbox_cost.setGeometry(QRect(260, 0, 71, 21))
        self.checkbox_assetcategory = QCheckBox(self.view_toggle_frame)
        self.checkbox_assetcategory.setObjectName(u"checkbox_assetcategory")
        self.checkbox_assetcategory.setGeometry(QRect(450, 0, 101, 21))
        self.checkbox_assettype = QCheckBox(self.view_toggle_frame)
        self.checkbox_assettype.setObjectName(u"checkbox_assettype")
        self.checkbox_assettype.setGeometry(QRect(100, 0, 91, 21))
        self.checkbox_assignedto = QCheckBox(self.view_toggle_frame)
        self.checkbox_assignedto.setObjectName(u"checkbox_assignedto")
        self.checkbox_assignedto.setGeometry(QRect(260, 20, 81, 21))
        self.checkbox_assetlocation = QCheckBox(self.view_toggle_frame)
        self.checkbox_assetlocation.setObjectName(u"checkbox_assetlocation")
        self.checkbox_assetlocation.setGeometry(QRect(350, 20, 91, 21))
        self.checkbox_deploymentdate = QCheckBox(self.view_toggle_frame)
        self.checkbox_deploymentdate.setObjectName(u"checkbox_deploymentdate")
        self.checkbox_deploymentdate.setGeometry(QRect(450, 20, 101, 21))
        self.checkbox_replacementdate = QCheckBox(self.view_toggle_frame)
        self.checkbox_replacementdate.setObjectName(u"checkbox_replacementdate")
        self.checkbox_replacementdate.setGeometry(QRect(560, 0, 111, 21))
        self.checkbox_notes = QCheckBox(self.view_toggle_frame)
        self.checkbox_notes.setObjectName(u"checkbox_notes")
        self.checkbox_notes.setGeometry(QRect(680, 0, 71, 21))
        self.checkbox_model = QCheckBox(self.view_toggle_frame)
        self.checkbox_model.setObjectName(u"checkbox_model")
        self.checkbox_model.setGeometry(QRect(190, 20, 61, 21))
        self.checkbox_view_retired_assets = QCheckBox(self.view_toggle_frame)
        self.checkbox_view_retired_assets.setObjectName(u"checkbox_view_retired_assets")
        self.checkbox_view_retired_assets.setGeometry(QRect(560, 20, 121, 21))
        self.checkbox_name = QCheckBox(self.view_toggle_frame)
        self.checkbox_name.setObjectName(u"checkbox_name")
        self.checkbox_name.setGeometry(QRect(350, 0, 91, 21))
        self.filter_column_button = QPushButton(self.stacked_view_db_page)
        self.filter_column_button.setObjectName(u"filter_column_button")
        self.filter_column_button.setGeometry(QRect(200, 30, 75, 23))
        self.filter_options_combobox = QComboBox(self.stacked_view_db_page)
        self.filter_options_combobox.setObjectName(u"filter_options_combobox")
        self.filter_options_combobox.setGeometry(QRect(90, 30, 101, 22))
        self.filter_user_text = QLineEdit(self.stacked_view_db_page)
        self.filter_user_text.setObjectName(u"filter_user_text")
        self.filter_user_text.setGeometry(QRect(290, 30, 151, 20))
        self.filter_clear_button = QPushButton(self.stacked_view_db_page)
        self.filter_clear_button.setObjectName(u"filter_clear_button")
        self.filter_clear_button.setGeometry(QRect(440, 30, 21, 20))
        self.stackedWidget.addWidget(self.stacked_view_db_page)
        self.stacked_add_to_db_page = QWidget()
        self.stacked_add_to_db_page.setObjectName(u"stacked_add_to_db_page")
        self.insert_serial_label = QLabel(self.stacked_add_to_db_page)
        self.insert_serial_label.setObjectName(u"insert_serial_label")
        self.insert_serial_label.setGeometry(QRect(20, 190, 110, 13))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.insert_serial_label.setFont(font)
        self.insert_serial_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_serial_text = QLineEdit(self.stacked_add_to_db_page)
        self.insert_serial_text.setObjectName(u"insert_serial_text")
        self.insert_serial_text.setGeometry(QRect(140, 187, 145, 25))
        self.insert_manufacture_label = QLabel(self.stacked_add_to_db_page)
        self.insert_manufacture_label.setObjectName(u"insert_manufacture_label")
        self.insert_manufacture_label.setGeometry(QRect(20, 150, 110, 20))
        self.insert_manufacture_label.setFont(font)
        self.insert_manufacture_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_cost_label = QLabel(self.stacked_add_to_db_page)
        self.insert_cost_label.setObjectName(u"insert_cost_label")
        self.insert_cost_label.setGeometry(QRect(20, 270, 110, 20))
        self.insert_cost_label.setFont(font)
        self.insert_cost_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_asset_category_label = QLabel(self.stacked_add_to_db_page)
        self.insert_asset_category_label.setObjectName(u"insert_asset_category_label")
        self.insert_asset_category_label.setGeometry(QRect(20, 410, 110, 20))
        self.insert_asset_category_label.setFont(font)
        self.insert_asset_category_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_asset_category_combobox = QComboBox(self.stacked_add_to_db_page)
        self.insert_asset_category_combobox.setObjectName(u"insert_asset_category_combobox")
        self.insert_asset_category_combobox.setGeometry(QRect(140, 410, 145, 25))
        self.insert_asset_type_label = QLabel(self.stacked_add_to_db_page)
        self.insert_asset_type_label.setObjectName(u"insert_asset_type_label")
        self.insert_asset_type_label.setGeometry(QRect(20, 110, 110, 20))
        self.insert_asset_type_label.setFont(font)
        self.insert_asset_type_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_asset_location_label = QLabel(self.stacked_add_to_db_page)
        self.insert_asset_location_label.setObjectName(u"insert_asset_location_label")
        self.insert_asset_location_label.setGeometry(QRect(20, 370, 110, 20))
        self.insert_asset_location_label.setFont(font)
        self.insert_asset_location_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_asset_location_combobox = QComboBox(self.stacked_add_to_db_page)
        self.insert_asset_location_combobox.setObjectName(u"insert_asset_location_combobox")
        self.insert_asset_location_combobox.setGeometry(QRect(140, 370, 145, 25))
        self.insert_assigned_to_label = QLabel(self.stacked_add_to_db_page)
        self.insert_assigned_to_label.setObjectName(u"insert_assigned_to_label")
        self.insert_assigned_to_label.setGeometry(QRect(20, 300, 110, 21))
        self.insert_assigned_to_label.setFont(font)
        self.insert_assigned_to_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_assigned_to_text = QLineEdit(self.stacked_add_to_db_page)
        self.insert_assigned_to_text.setObjectName(u"insert_assigned_to_text")
        self.insert_assigned_to_text.setGeometry(QRect(140, 300, 145, 25))
        self.insert_asset_type_combobox = QComboBox(self.stacked_add_to_db_page)
        self.insert_asset_type_combobox.setObjectName(u"insert_asset_type_combobox")
        self.insert_asset_type_combobox.setGeometry(QRect(140, 110, 145, 25))
        self.insert_deployment_date_label = QLabel(self.stacked_add_to_db_page)
        self.insert_deployment_date_label.setObjectName(u"insert_deployment_date_label")
        self.insert_deployment_date_label.setGeometry(QRect(20, 460, 110, 21))
        self.insert_deployment_date_label.setFont(font)
        self.insert_deployment_date_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_deployment_date_fmt = QDateEdit(self.stacked_add_to_db_page)
        self.insert_deployment_date_fmt.setObjectName(u"insert_deployment_date_fmt")
        self.insert_deployment_date_fmt.setGeometry(QRect(140, 460, 110, 22))
        self.insert_deployment_date_fmt.setCalendarPopup(True)
        self.insert_replacement_date_fmt = QDateEdit(self.stacked_add_to_db_page)
        self.insert_replacement_date_fmt.setObjectName(u"insert_replacement_date_fmt")
        self.insert_replacement_date_fmt.setGeometry(QRect(140, 500, 110, 22))
        self.insert_replacement_date_fmt.setCalendarPopup(True)
        self.insert_replacement_date_label = QLabel(self.stacked_add_to_db_page)
        self.insert_replacement_date_label.setObjectName(u"insert_replacement_date_label")
        self.insert_replacement_date_label.setGeometry(QRect(9, 500, 121, 21))
        self.insert_replacement_date_label.setFont(font)
        self.insert_replacement_date_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_notes_label = QLabel(self.stacked_add_to_db_page)
        self.insert_notes_label.setObjectName(u"insert_notes_label")
        self.insert_notes_label.setGeometry(QRect(350, 110, 110, 13))
        self.insert_notes_label.setFont(font)
        self.insert_notes_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_notes_text = QTextEdit(self.stacked_add_to_db_page)
        self.insert_notes_text.setObjectName(u"insert_notes_text")
        self.insert_notes_text.setGeometry(QRect(480, 110, 291, 191))
        self.insert_status_label = QLabel(self.stacked_add_to_db_page)
        self.insert_status_label.setObjectName(u"insert_status_label")
        self.insert_status_label.setGeometry(QRect(20, 540, 110, 21))
        self.insert_status_label.setFont(font)
        self.insert_status_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_status_bool = QComboBox(self.stacked_add_to_db_page)
        self.insert_status_bool.setObjectName(u"insert_status_bool")
        self.insert_status_bool.setGeometry(QRect(140, 540, 91, 22))
        self.insert_cost_spinbox = QDoubleSpinBox(self.stacked_add_to_db_page)
        self.insert_cost_spinbox.setObjectName(u"insert_cost_spinbox")
        self.insert_cost_spinbox.setGeometry(QRect(140, 270, 111, 22))
        self.insert_asset_category_add_option = QPushButton(self.stacked_add_to_db_page)
        self.insert_asset_category_add_option.setObjectName(u"insert_asset_category_add_option")
        self.insert_asset_category_add_option.setGeometry(QRect(290, 410, 25, 25))
        self.insert_asset_type_add_option = QPushButton(self.stacked_add_to_db_page)
        self.insert_asset_type_add_option.setObjectName(u"insert_asset_type_add_option")
        self.insert_asset_type_add_option.setGeometry(QRect(290, 110, 25, 25))
        self.insert_asset_location_add_option = QPushButton(self.stacked_add_to_db_page)
        self.insert_asset_location_add_option.setObjectName(u"insert_asset_location_add_option")
        self.insert_asset_location_add_option.setGeometry(QRect(290, 370, 25, 25))
        self.insert_asset_location_add_option.setLayoutDirection(Qt.LeftToRight)
        self.insert_insert_button = QPushButton(self.stacked_add_to_db_page)
        self.insert_insert_button.setObjectName(u"insert_insert_button")
        self.insert_insert_button.setGeometry(QRect(130, 580, 131, 31))
        self.insert_clear_selections_button = QPushButton(self.stacked_add_to_db_page)
        self.insert_clear_selections_button.setObjectName(u"insert_clear_selections_button")
        self.insert_clear_selections_button.setGeometry(QRect(1070, 590, 75, 23))
        self.insert_model_label = QLabel(self.stacked_add_to_db_page)
        self.insert_model_label.setObjectName(u"insert_model_label")
        self.insert_model_label.setGeometry(QRect(20, 230, 110, 21))
        self.insert_model_label.setFont(font)
        self.insert_model_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_model_text = QLineEdit(self.stacked_add_to_db_page)
        self.insert_model_text.setObjectName(u"insert_model_text")
        self.insert_model_text.setGeometry(QRect(140, 230, 145, 25))
        self.label = QLabel(self.stacked_add_to_db_page)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(140, 440, 81, 16))
        self.insert_manufacturer_combobox = QComboBox(self.stacked_add_to_db_page)
        self.insert_manufacturer_combobox.setObjectName(u"insert_manufacturer_combobox")
        self.insert_manufacturer_combobox.setGeometry(QRect(140, 150, 145, 25))
        self.insert_manufacturer_add_option = QPushButton(self.stacked_add_to_db_page)
        self.insert_manufacturer_add_option.setObjectName(u"insert_manufacturer_add_option")
        self.insert_manufacturer_add_option.setGeometry(QRect(290, 150, 25, 25))
        self.insert_conditional_status_frame = QFrame(self.stacked_add_to_db_page)
        self.insert_conditional_status_frame.setObjectName(u"insert_conditional_status_frame")
        self.insert_conditional_status_frame.setGeometry(QRect(300, 500, 210, 40))
        self.insert_conditional_status_frame.setFrameShape(QFrame.StyledPanel)
        self.insert_conditional_status_frame.setFrameShadow(QFrame.Raised)
        self.insert_serial_is_unique_button = QPushButton(self.stacked_add_to_db_page)
        self.insert_serial_is_unique_button.setObjectName(u"insert_serial_is_unique_button")
        self.insert_serial_is_unique_button.setGeometry(QRect(290, 190, 121, 23))
        self.insert_conditional_retirement_date_label = QLabel(self.stacked_add_to_db_page)
        self.insert_conditional_retirement_date_label.setObjectName(u"insert_conditional_retirement_date_label")
        self.insert_conditional_retirement_date_label.setGeometry(QRect(310, 530, 81, 21))
        font1 = QFont()
        font1.setBold(False)
        font1.setWeight(50)
        self.insert_conditional_retirement_date_label.setFont(font1)
        self.insert_conditional_retirement_date_fmt = QDateEdit(self.stacked_add_to_db_page)
        self.insert_conditional_retirement_date_fmt.setObjectName(u"insert_conditional_retirement_date_fmt")
        self.insert_conditional_retirement_date_fmt.setGeometry(QRect(400, 530, 110, 22))
        self.insert_conditional_retirement_date_fmt.setCalendarPopup(True)
        self.insert_name_label = QLabel(self.stacked_add_to_db_page)
        self.insert_name_label.setObjectName(u"insert_name_label")
        self.insert_name_label.setGeometry(QRect(20, 335, 110, 21))
        self.insert_name_label.setFont(font)
        self.insert_name_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.insert_name_text = QLineEdit(self.stacked_add_to_db_page)
        self.insert_name_text.setObjectName(u"insert_name_text")
        self.insert_name_text.setGeometry(QRect(140, 335, 145, 25))
        self.stackedWidget.addWidget(self.stacked_add_to_db_page)
        self.insert_serial_label.raise_()
        self.insert_manufacture_label.raise_()
        self.insert_cost_label.raise_()
        self.insert_asset_category_label.raise_()
        self.insert_asset_type_label.raise_()
        self.insert_asset_location_label.raise_()
        self.insert_assigned_to_label.raise_()
        self.insert_deployment_date_label.raise_()
        self.insert_replacement_date_label.raise_()
        self.insert_notes_label.raise_()
        self.insert_status_label.raise_()
        self.insert_status_bool.raise_()
        self.insert_asset_category_add_option.raise_()
        self.insert_asset_type_add_option.raise_()
        self.insert_asset_location_add_option.raise_()
        self.insert_insert_button.raise_()
        self.insert_clear_selections_button.raise_()
        self.insert_model_label.raise_()
        self.insert_notes_text.raise_()
        self.insert_replacement_date_fmt.raise_()
        self.insert_deployment_date_fmt.raise_()
        self.insert_assigned_to_text.raise_()
        self.insert_asset_location_combobox.raise_()
        self.insert_asset_type_combobox.raise_()
        self.insert_asset_category_combobox.raise_()
        self.insert_cost_spinbox.raise_()
        self.insert_model_text.raise_()
        self.insert_serial_text.raise_()
        self.label.raise_()
        self.insert_manufacturer_combobox.raise_()
        self.insert_manufacturer_add_option.raise_()
        self.insert_conditional_status_frame.raise_()
        self.insert_serial_is_unique_button.raise_()
        self.insert_conditional_retirement_date_label.raise_()
        self.insert_conditional_retirement_date_fmt.raise_()
        self.insert_name_label.raise_()
        self.insert_name_text.raise_()
        self.stacked_analytic_page = QWidget()
        self.stacked_analytic_page.setObjectName(u"stacked_analytic_page")
        self.analytics_graph_frame_top = QFrame(self.stacked_analytic_page)
        self.analytics_graph_frame_top.setObjectName(u"analytics_graph_frame_top")
        self.analytics_graph_frame_top.setGeometry(QRect(20, 30, 1141, 310))
        self.analytics_graph_frame_top.setFrameShape(QFrame.StyledPanel)
        self.analytics_graph_frame_top.setFrameShadow(QFrame.Raised)
        self.analytics_field_combobox_top = QComboBox(self.analytics_graph_frame_top)
        self.analytics_field_combobox_top.setObjectName(u"analytics_field_combobox_top")
        self.analytics_field_combobox_top.setGeometry(QRect(20, 20, 161, 22))
        self.analytics_graph_top = QFrame(self.analytics_graph_frame_top)
        self.analytics_graph_top.setObjectName(u"analytics_graph_top")
        self.analytics_graph_top.setGeometry(QRect(190, 5, 921, 291))
        self.analytics_graph_top.setFrameShape(QFrame.StyledPanel)
        self.analytics_graph_top.setFrameShadow(QFrame.Raised)
        self.analytics_field_combobox_top_2 = QComboBox(self.analytics_graph_frame_top)
        self.analytics_field_combobox_top_2.setObjectName(u"analytics_field_combobox_top_2")
        self.analytics_field_combobox_top_2.setGeometry(QRect(20, 70, 161, 22))
        self.analytics_export_top_button = QPushButton(self.analytics_graph_frame_top)
        self.analytics_export_top_button.setObjectName(u"analytics_export_top_button")
        self.analytics_export_top_button.setGeometry(QRect(20, 110, 75, 23))
        self.analytics_x_axis_label = QLabel(self.analytics_graph_frame_top)
        self.analytics_x_axis_label.setObjectName(u"analytics_x_axis_label")
        self.analytics_x_axis_label.setGeometry(QRect(20, 150, 71, 16))
        self.analytics_x_axis_label.setToolTipDuration(-1)
        self.analytics_x_axis_text = QLineEdit(self.analytics_graph_frame_top)
        self.analytics_x_axis_text.setObjectName(u"analytics_x_axis_text")
        self.analytics_x_axis_text.setGeometry(QRect(20, 170, 161, 20))
        self.analytics_x_axis_text.setToolTipDuration(-1)
        self.analytics_y_axis_text = QLineEdit(self.analytics_graph_frame_top)
        self.analytics_y_axis_text.setObjectName(u"analytics_y_axis_text")
        self.analytics_y_axis_text.setGeometry(QRect(20, 220, 161, 20))
        self.analytics_y_axis_label = QLabel(self.analytics_graph_frame_top)
        self.analytics_y_axis_label.setObjectName(u"analytics_y_axis_label")
        self.analytics_y_axis_label.setGeometry(QRect(20, 200, 71, 16))
        self.analytics_update_top_view_button = QPushButton(self.analytics_graph_frame_top)
        self.analytics_update_top_view_button.setObjectName(u"analytics_update_top_view_button")
        self.analytics_update_top_view_button.setGeometry(QRect(20, 260, 91, 21))
        self.analytics_graph_frame_top_2 = QFrame(self.stacked_analytic_page)
        self.analytics_graph_frame_top_2.setObjectName(u"analytics_graph_frame_top_2")
        self.analytics_graph_frame_top_2.setGeometry(QRect(620, 350, 541, 310))
        self.analytics_graph_frame_top_2.setFrameShape(QFrame.StyledPanel)
        self.analytics_graph_frame_top_2.setFrameShadow(QFrame.Raised)
        self.analytics_field_combobox_bottom = QComboBox(self.analytics_graph_frame_top_2)
        self.analytics_field_combobox_bottom.setObjectName(u"analytics_field_combobox_bottom")
        self.analytics_field_combobox_bottom.setGeometry(QRect(20, 20, 161, 22))
        self.analytics_field_combobox_bottom_2 = QComboBox(self.analytics_graph_frame_top_2)
        self.analytics_field_combobox_bottom_2.setObjectName(u"analytics_field_combobox_bottom_2")
        self.analytics_field_combobox_bottom_2.setGeometry(QRect(20, 70, 161, 22))
        self.analytics_graph_bottom = QFrame(self.analytics_graph_frame_top_2)
        self.analytics_graph_bottom.setObjectName(u"analytics_graph_bottom")
        self.analytics_graph_bottom.setGeometry(QRect(10, 5, 521, 301))
        self.analytics_graph_bottom.setFrameShape(QFrame.StyledPanel)
        self.analytics_graph_bottom.setFrameShadow(QFrame.Raised)
        self.analytics_export_bottom_button = QPushButton(self.analytics_graph_frame_top_2)
        self.analytics_export_bottom_button.setObjectName(u"analytics_export_bottom_button")
        self.analytics_export_bottom_button.setGeometry(QRect(20, 110, 75, 23))
        self.analytics_graph_bottom.raise_()
        self.analytics_field_combobox_bottom_2.raise_()
        self.analytics_field_combobox_bottom.raise_()
        self.analytics_export_bottom_button.raise_()
        self.calendarWidget = QCalendarWidget(self.stacked_analytic_page)
        self.calendarWidget.setObjectName(u"calendarWidget")
        self.calendarWidget.setGeometry(QRect(20, 340, 590, 311))
        self.stackedWidget.addWidget(self.stacked_analytic_page)
        self.stacked_reports_page = QWidget()
        self.stacked_reports_page.setObjectName(u"stacked_reports_page")
        self.reports_total_asset_value_label = QLabel(self.stacked_reports_page)
        self.reports_total_asset_value_label.setObjectName(u"reports_total_asset_value_label")
        self.reports_total_asset_value_label.setGeometry(QRect(880, 20, 251, 41))
        font2 = QFont()
        font2.setFamily(u"Arial")
        font2.setPointSize(24)
        self.reports_total_asset_value_label.setFont(font2)
        self.reports_dollarsign_label = QLabel(self.stacked_reports_page)
        self.reports_dollarsign_label.setObjectName(u"reports_dollarsign_label")
        self.reports_dollarsign_label.setGeometry(QRect(880, 60, 16, 41))
        font3 = QFont()
        font3.setPointSize(24)
        self.reports_dollarsign_label.setFont(font3)
        self.reports_asset_integer_label = QLabel(self.stacked_reports_page)
        self.reports_asset_integer_label.setObjectName(u"reports_asset_integer_label")
        self.reports_asset_integer_label.setGeometry(QRect(900, 60, 221, 41))
        self.reports_asset_integer_label.setFont(font2)
        self.reports_asset_integer_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.reports_export_frame = QFrame(self.stacked_reports_page)
        self.reports_export_frame.setObjectName(u"reports_export_frame")
        self.reports_export_frame.setGeometry(QRect(40, 30, 361, 621))
        self.reports_export_frame.setStyleSheet(u"")
        self.reports_export_frame.setFrameShape(QFrame.StyledPanel)
        self.reports_export_frame.setFrameShadow(QFrame.Raised)
        self.reports_export_main_label = QLabel(self.reports_export_frame)
        self.reports_export_main_label.setObjectName(u"reports_export_main_label")
        self.reports_export_main_label.setGeometry(QRect(10, 20, 341, 31))
        self.reports_export_main_label.setFont(font2)
        self.reports_export_main_label.setAlignment(Qt.AlignCenter)
        self.reports_export_export_file_label = QLabel(self.reports_export_frame)
        self.reports_export_export_file_label.setObjectName(u"reports_export_export_file_label")
        self.reports_export_export_file_label.setGeometry(QRect(20, 70, 81, 16))
        self.reports_export_file_combobox = QComboBox(self.reports_export_frame)
        self.reports_export_file_combobox.setObjectName(u"reports_export_file_combobox")
        self.reports_export_file_combobox.setGeometry(QRect(120, 70, 69, 22))
        self.line = QFrame(self.reports_export_frame)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 110, 341, 2))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(self.reports_export_frame)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(10, 170, 341, 2))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.reports_export_export_active_radio = QRadioButton(self.reports_export_frame)
        self.reports_export_export_active_radio.setObjectName(u"reports_export_export_active_radio")
        self.reports_export_export_active_radio.setGeometry(QRect(10, 130, 131, 17))
        self.reports_export_export_retired_radio = QRadioButton(self.reports_export_frame)
        self.reports_export_export_retired_radio.setObjectName(u"reports_export_export_retired_radio")
        self.reports_export_export_retired_radio.setGeometry(QRect(10, 190, 131, 17))
        self.line_3 = QFrame(self.reports_export_frame)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(10, 230, 341, 2))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.reports_export_export_location_radio = QRadioButton(self.reports_export_frame)
        self.reports_export_export_location_radio.setObjectName(u"reports_export_export_location_radio")
        self.reports_export_export_location_radio.setGeometry(QRect(10, 330, 151, 17))
        self.reports_export_location_combobox = QComboBox(self.reports_export_frame)
        self.reports_export_location_combobox.setObjectName(u"reports_export_location_combobox")
        self.reports_export_location_combobox.setGeometry(QRect(180, 330, 101, 22))
        self.line_4 = QFrame(self.reports_export_frame)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(10, 300, 341, 2))
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.reports_export_export_due_replacement_radio = QRadioButton(self.reports_export_frame)
        self.reports_export_export_due_replacement_radio.setObjectName(u"reports_export_export_due_replacement_radio")
        self.reports_export_export_due_replacement_radio.setGeometry(QRect(10, 250, 171, 17))
        self.reports_export_export_due_replacement_combo = QComboBox(self.reports_export_frame)
        self.reports_export_export_due_replacement_combo.setObjectName(u"reports_export_export_due_replacement_combo")
        self.reports_export_export_due_replacement_combo.setGeometry(QRect(180, 250, 101, 22))
        self.line_5 = QFrame(self.reports_export_frame)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(10, 390, 341, 2))
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.reports_export_main_export_button = QPushButton(self.reports_export_frame)
        self.reports_export_main_export_button.setObjectName(u"reports_export_main_export_button")
        self.reports_export_main_export_button.setGeometry(QRect(40, 490, 281, 31))
        self.reports_export_status_label = QLabel(self.reports_export_frame)
        self.reports_export_status_label.setObjectName(u"reports_export_status_label")
        self.reports_export_status_label.setGeometry(QRect(10, 550, 51, 16))
        self.reports_export_status_content = QLabel(self.reports_export_frame)
        self.reports_export_status_content.setObjectName(u"reports_export_status_content")
        self.reports_export_status_content.setGeometry(QRect(10, 570, 241, 31))
        self.export_file_path_choice = QLineEdit(self.reports_export_frame)
        self.export_file_path_choice.setObjectName(u"export_file_path_choice")
        self.export_file_path_choice.setGeometry(QRect(110, 460, 181, 20))
        self.export_file_dialog = QPushButton(self.reports_export_frame)
        self.export_file_dialog.setObjectName(u"export_file_dialog")
        self.export_file_dialog.setGeometry(QRect(290, 460, 31, 20))
        self.reports_export_path_label = QLabel(self.reports_export_frame)
        self.reports_export_path_label.setObjectName(u"reports_export_path_label")
        self.reports_export_path_label.setGeometry(QRect(30, 460, 71, 16))
        self.reports_export_path_label.setLayoutDirection(Qt.LeftToRight)
        self.reports_export_path_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.stacked_reports_page)
        self.stacked_settings_page = QWidget()
        self.stacked_settings_page.setObjectName(u"stacked_settings_page")
        self.settings_backup_dir_label = QLabel(self.stacked_settings_page)
        self.settings_backup_dir_label.setObjectName(u"settings_backup_dir_label")
        self.settings_backup_dir_label.setGeometry(QRect(10, 70, 181, 21))
        font4 = QFont()
        font4.setPointSize(10)
        self.settings_backup_dir_label.setFont(font4)
        self.settings_backup_dir_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.settings_backup_dir_text = QLineEdit(self.stacked_settings_page)
        self.settings_backup_dir_text.setObjectName(u"settings_backup_dir_text")
        self.settings_backup_dir_text.setGeometry(QRect(200, 70, 311, 20))
        self.settings_darkmode_label = QLabel(self.stacked_settings_page)
        self.settings_darkmode_label.setObjectName(u"settings_darkmode_label")
        self.settings_darkmode_label.setGeometry(QRect(10, 100, 181, 21))
        self.settings_darkmode_label.setFont(font4)
        self.settings_darkmode_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.settings_darkmode_checkbox = QCheckBox(self.stacked_settings_page)
        self.settings_darkmode_checkbox.setObjectName(u"settings_darkmode_checkbox")
        self.settings_darkmode_checkbox.setGeometry(QRect(200, 103, 16, 17))
        self.settings_update_button = QPushButton(self.stacked_settings_page)
        self.settings_update_button.setObjectName(u"settings_update_button")
        self.settings_update_button.setGeometry(QRect(1060, 610, 75, 23))
        self.settings_report_auto_open_label = QLabel(self.stacked_settings_page)
        self.settings_report_auto_open_label.setObjectName(u"settings_report_auto_open_label")
        self.settings_report_auto_open_label.setGeometry(QRect(10, 127, 181, 21))
        self.settings_report_auto_open_label.setFont(font4)
        self.settings_report_auto_open_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.settings_report_auto_open_checkbox = QCheckBox(self.stacked_settings_page)
        self.settings_report_auto_open_checkbox.setObjectName(u"settings_report_auto_open_checkbox")
        self.settings_report_auto_open_checkbox.setGeometry(QRect(200, 130, 16, 17))
        self.settings_file_dialog_button = QPushButton(self.stacked_settings_page)
        self.settings_file_dialog_button.setObjectName(u"settings_file_dialog_button")
        self.settings_file_dialog_button.setGeometry(QRect(510, 70, 21, 21))
        self.stackedWidget.addWidget(self.stacked_settings_page)
        self.ham_button_view = QPushButton(self.centralwidget)
        self.ham_button_view.setObjectName(u"ham_button_view")
        self.ham_button_view.setGeometry(QRect(0, 40, 81, 50))
        self.ham_button_view.setFlat(False)
        self.ham_button_insert = QPushButton(self.centralwidget)
        self.ham_button_insert.setObjectName(u"ham_button_insert")
        self.ham_button_insert.setGeometry(QRect(0, 90, 81, 50))
        self.ham_button_insert.setFlat(False)
        self.ham_button_analytics = QPushButton(self.centralwidget)
        self.ham_button_analytics.setObjectName(u"ham_button_analytics")
        self.ham_button_analytics.setGeometry(QRect(0, 140, 81, 50))
        self.ham_button_analytics.setFlat(False)
        self.ham_button_reports = QPushButton(self.centralwidget)
        self.ham_button_reports.setObjectName(u"ham_button_reports")
        self.ham_button_reports.setGeometry(QRect(0, 190, 81, 50))
        self.ham_button_reports.setFlat(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1302, 21))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        MainWindow.setMenuBar(self.menubar)
        QWidget.setTabOrder(self.insert_serial_text, self.insert_model_text)
        QWidget.setTabOrder(self.insert_model_text, self.insert_cost_spinbox)
        QWidget.setTabOrder(self.insert_cost_spinbox, self.insert_asset_category_combobox)
        QWidget.setTabOrder(self.insert_asset_category_combobox, self.insert_asset_type_combobox)
        QWidget.setTabOrder(self.insert_asset_type_combobox, self.insert_asset_location_combobox)
        QWidget.setTabOrder(self.insert_asset_location_combobox, self.insert_assigned_to_text)
        QWidget.setTabOrder(self.insert_assigned_to_text, self.insert_deployment_date_fmt)
        QWidget.setTabOrder(self.insert_deployment_date_fmt, self.insert_replacement_date_fmt)
        QWidget.setTabOrder(self.insert_replacement_date_fmt, self.insert_notes_text)
        QWidget.setTabOrder(self.insert_notes_text, self.insert_insert_button)
        QWidget.setTabOrder(self.insert_insert_button, self.insert_clear_selections_button)
        QWidget.setTabOrder(self.insert_clear_selections_button, self.checkbox_assignedto)
        QWidget.setTabOrder(self.checkbox_assignedto, self.checkbox_assetlocation)
        QWidget.setTabOrder(self.checkbox_assetlocation, self.checkbox_deploymentdate)
        QWidget.setTabOrder(self.checkbox_deploymentdate, self.checkbox_replacementdate)
        QWidget.setTabOrder(self.checkbox_replacementdate, self.checkbox_notes)
        QWidget.setTabOrder(self.checkbox_notes, self.checkbox_model)
        QWidget.setTabOrder(self.checkbox_model, self.filter_column_button)
        QWidget.setTabOrder(self.filter_column_button, self.filter_options_combobox)
        QWidget.setTabOrder(self.filter_options_combobox, self.filter_user_text)
        QWidget.setTabOrder(self.filter_user_text, self.filter_clear_button)
        QWidget.setTabOrder(self.filter_clear_button, self.ham_button_insert)
        QWidget.setTabOrder(self.ham_button_insert, self.ham_button_analytics)
        QWidget.setTabOrder(self.ham_button_analytics, self.main_table)
        QWidget.setTabOrder(self.main_table, self.refresh_table_button)
        QWidget.setTabOrder(self.refresh_table_button, self.view_columns_button)
        QWidget.setTabOrder(self.view_columns_button, self.checkbox_serial)
        QWidget.setTabOrder(self.checkbox_serial, self.checkbox_manufacturer)
        QWidget.setTabOrder(self.checkbox_manufacturer, self.checkbox_cost)
        QWidget.setTabOrder(self.checkbox_cost, self.insert_status_bool)
        QWidget.setTabOrder(self.insert_status_bool, self.ham_button_view)
        QWidget.setTabOrder(self.ham_button_view, self.insert_asset_category_add_option)
        QWidget.setTabOrder(self.insert_asset_category_add_option, self.insert_asset_type_add_option)
        QWidget.setTabOrder(self.insert_asset_type_add_option, self.insert_asset_location_add_option)
        QWidget.setTabOrder(self.insert_asset_location_add_option, self.checkbox_assetcategory)
        QWidget.setTabOrder(self.checkbox_assetcategory, self.checkbox_assettype)
        QWidget.setTabOrder(self.checkbox_assettype, self.ham_button_reports)
        QWidget.setTabOrder(self.ham_button_reports, self.analytics_field_combobox_top)
        QWidget.setTabOrder(self.analytics_field_combobox_top, self.analytics_field_combobox_top_2)
        QWidget.setTabOrder(self.analytics_field_combobox_top_2, self.analytics_export_top_button)
        QWidget.setTabOrder(self.analytics_export_top_button, self.analytics_x_axis_text)
        QWidget.setTabOrder(self.analytics_x_axis_text, self.analytics_y_axis_text)
        QWidget.setTabOrder(self.analytics_y_axis_text, self.analytics_update_top_view_button)
        QWidget.setTabOrder(self.analytics_update_top_view_button, self.analytics_field_combobox_bottom)
        QWidget.setTabOrder(self.analytics_field_combobox_bottom, self.analytics_field_combobox_bottom_2)
        QWidget.setTabOrder(self.analytics_field_combobox_bottom_2, self.analytics_export_bottom_button)
        QWidget.setTabOrder(self.analytics_export_bottom_button, self.calendarWidget)
        QWidget.setTabOrder(self.calendarWidget, self.reports_export_file_combobox)
        QWidget.setTabOrder(self.reports_export_file_combobox, self.reports_export_export_active_radio)
        QWidget.setTabOrder(self.reports_export_export_active_radio, self.reports_export_export_retired_radio)
        QWidget.setTabOrder(self.reports_export_export_retired_radio, self.reports_export_export_location_radio)
        QWidget.setTabOrder(self.reports_export_export_location_radio, self.reports_export_location_combobox)
        QWidget.setTabOrder(self.reports_export_location_combobox, self.reports_export_export_due_replacement_radio)
        QWidget.setTabOrder(self.reports_export_export_due_replacement_radio, self.reports_export_export_due_replacement_combo)
        QWidget.setTabOrder(self.reports_export_export_due_replacement_combo, self.reports_export_main_export_button)
        QWidget.setTabOrder(self.reports_export_main_export_button, self.export_file_path_choice)
        QWidget.setTabOrder(self.export_file_path_choice, self.export_file_dialog)
        QWidget.setTabOrder(self.export_file_dialog, self.settings_backup_dir_text)
        QWidget.setTabOrder(self.settings_backup_dir_text, self.settings_darkmode_checkbox)
        QWidget.setTabOrder(self.settings_darkmode_checkbox, self.settings_update_button)
        QWidget.setTabOrder(self.settings_update_button, self.settings_report_auto_open_checkbox)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionCreate_Backup)
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionClose_ALT_F4)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Invisible Man", None))
        self.actionInsert.setText(QCoreApplication.translate("MainWindow", u"Insert", None))
        self.actionSettings.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionCreate_Backup.setText(QCoreApplication.translate("MainWindow", u"Create Backup", None))
        self.actionClose_ALT_F4.setText(QCoreApplication.translate("MainWindow", u"Close                  ALT-F4", None))
        self.refresh_table_button.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.view_columns_button.setText(QCoreApplication.translate("MainWindow", u"View", None))
        self.checkbox_serial.setText(QCoreApplication.translate("MainWindow", u"Serial", None))
        self.checkbox_manufacturer.setText(QCoreApplication.translate("MainWindow", u"Manufacturer", None))
        self.checkbox_cost.setText(QCoreApplication.translate("MainWindow", u"Cost", None))
        self.checkbox_assetcategory.setText(QCoreApplication.translate("MainWindow", u"Asset Category", None))
        self.checkbox_assettype.setText(QCoreApplication.translate("MainWindow", u"Asset Type", None))
        self.checkbox_assignedto.setText(QCoreApplication.translate("MainWindow", u"Assigned To", None))
        self.checkbox_assetlocation.setText(QCoreApplication.translate("MainWindow", u"Asset Location", None))
        self.checkbox_deploymentdate.setText(QCoreApplication.translate("MainWindow", u"Deployment Date", None))
        self.checkbox_replacementdate.setText(QCoreApplication.translate("MainWindow", u"Replacement Date", None))
        self.checkbox_notes.setText(QCoreApplication.translate("MainWindow", u"Notes", None))
        self.checkbox_model.setText(QCoreApplication.translate("MainWindow", u"Model", None))
        self.checkbox_view_retired_assets.setText(QCoreApplication.translate("MainWindow", u"Retired Assets", None))
        self.checkbox_name.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.filter_column_button.setText(QCoreApplication.translate("MainWindow", u"Apply Filter", None))
        self.filter_clear_button.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.insert_serial_label.setText(QCoreApplication.translate("MainWindow", u"Serial #", None))
        self.insert_serial_text.setText("")
        self.insert_manufacture_label.setText(QCoreApplication.translate("MainWindow", u"Manufacturer", None))
        self.insert_cost_label.setText(QCoreApplication.translate("MainWindow", u"Cost", None))
        self.insert_asset_category_label.setText(QCoreApplication.translate("MainWindow", u"Asset Category", None))
        self.insert_asset_type_label.setText(QCoreApplication.translate("MainWindow", u"Asset Type", None))
        self.insert_asset_location_label.setText(QCoreApplication.translate("MainWindow", u"Asset Location", None))
        self.insert_assigned_to_label.setText(QCoreApplication.translate("MainWindow", u"Assigned To", None))
        self.insert_assigned_to_text.setText("")
        self.insert_deployment_date_label.setText(QCoreApplication.translate("MainWindow", u"Deployment Date", None))
        self.insert_replacement_date_label.setText(QCoreApplication.translate("MainWindow", u"Replacement Date", None))
        self.insert_notes_label.setText(QCoreApplication.translate("MainWindow", u"Notes", None))
        self.insert_status_label.setText(QCoreApplication.translate("MainWindow", u"Status", None))
        self.insert_asset_category_add_option.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.insert_asset_type_add_option.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.insert_asset_location_add_option.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.insert_insert_button.setText(QCoreApplication.translate("MainWindow", u"Insert!", None))
        self.insert_clear_selections_button.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.insert_model_label.setText(QCoreApplication.translate("MainWindow", u"Model", None))
        self.insert_model_text.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"YYYY-MM-DD", None))
        self.insert_manufacturer_add_option.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.insert_serial_is_unique_button.setText(QCoreApplication.translate("MainWindow", u"cant import empty SN", None))
        self.insert_conditional_retirement_date_label.setText(QCoreApplication.translate("MainWindow", u"Retirement Date", None))
        self.insert_name_label.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.insert_name_text.setText("")
        self.analytics_export_top_button.setText(QCoreApplication.translate("MainWindow", u"Export", None))
#if QT_CONFIG(tooltip)
        self.analytics_x_axis_label.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.analytics_x_axis_label.setText(QCoreApplication.translate("MainWindow", u"X Axis Values", None))
#if QT_CONFIG(tooltip)
        self.analytics_x_axis_text.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.analytics_y_axis_text.setText("")
        self.analytics_y_axis_label.setText(QCoreApplication.translate("MainWindow", u"Y Axis Values", None))
        self.analytics_update_top_view_button.setText(QCoreApplication.translate("MainWindow", u"Update View", None))
        self.analytics_export_bottom_button.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.reports_total_asset_value_label.setText(QCoreApplication.translate("MainWindow", u"Total Asset Value", None))
        self.reports_dollarsign_label.setText(QCoreApplication.translate("MainWindow", u"$", None))
        self.reports_asset_integer_label.setText(QCoreApplication.translate("MainWindow", u"10,000", None))
        self.reports_export_main_label.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.reports_export_export_file_label.setText(QCoreApplication.translate("MainWindow", u"Export File Type", None))
        self.reports_export_export_active_radio.setText(QCoreApplication.translate("MainWindow", u"Export Active Assets", None))
        self.reports_export_export_retired_radio.setText(QCoreApplication.translate("MainWindow", u"Export Retired Assets", None))
        self.reports_export_export_location_radio.setText(QCoreApplication.translate("MainWindow", u"Export Active By Location", None))
        self.reports_export_export_due_replacement_radio.setText(QCoreApplication.translate("MainWindow", u"Assets Due For Replacement", None))
        self.reports_export_main_export_button.setText(QCoreApplication.translate("MainWindow", u"Export!", None))
        self.reports_export_status_label.setText(QCoreApplication.translate("MainWindow", u"Status:", None))
        self.reports_export_status_content.setText("")
        self.export_file_dialog.setText(QCoreApplication.translate("MainWindow", u"..", None))
        self.reports_export_path_label.setText(QCoreApplication.translate("MainWindow", u"Export Path:", None))
        self.settings_backup_dir_label.setText(QCoreApplication.translate("MainWindow", u"Backup Directory Path", None))
        self.settings_darkmode_label.setText(QCoreApplication.translate("MainWindow", u"Dark Mode", None))
        self.settings_darkmode_checkbox.setText(QCoreApplication.translate("MainWindow", u"CheckBox", None))
        self.settings_update_button.setText(QCoreApplication.translate("MainWindow", u"Update", None))
        self.settings_report_auto_open_label.setText(QCoreApplication.translate("MainWindow", u"Auto-open report in explorer", None))
        self.settings_report_auto_open_checkbox.setText(QCoreApplication.translate("MainWindow", u"CheckBox", None))
        self.settings_file_dialog_button.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.ham_button_view.setText(QCoreApplication.translate("MainWindow", u"Assets", None))
        self.ham_button_insert.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.ham_button_analytics.setText(QCoreApplication.translate("MainWindow", u"Analytics", None))
        self.ham_button_reports.setText(QCoreApplication.translate("MainWindow", u"Reports", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
    # retranslateUi

